// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD4Emmbi769laYvWIMCVJgzT0_D1RB-LU',
    appId: '1:625821260762:web:773d864b8f80588434fee3',
    messagingSenderId: '625821260762',
    projectId: 'interactive-4b6a3',
    authDomain: 'interactive-4b6a3.firebaseapp.com',
    storageBucket: 'interactive-4b6a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoiYLdchCJKM3tzlRwuLaz8Woouitdmbw',
    appId: '1:625821260762:android:2352042cc90c0bfb34fee3',
    messagingSenderId: '625821260762',
    projectId: 'interactive-4b6a3',
    storageBucket: 'interactive-4b6a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjPxpcDFAMsZ-4bpMeaQ9oEA-jCxwaEtI',
    appId: '1:625821260762:ios:2bed69fa12661e0934fee3',
    messagingSenderId: '625821260762',
    projectId: 'interactive-4b6a3',
    storageBucket: 'interactive-4b6a3.appspot.com',
    iosBundleId: 'com.example.interactive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjPxpcDFAMsZ-4bpMeaQ9oEA-jCxwaEtI',
    appId: '1:625821260762:ios:64e15bab1d83de9134fee3',
    messagingSenderId: '625821260762',
    projectId: 'interactive-4b6a3',
    storageBucket: 'interactive-4b6a3.appspot.com',
    iosBundleId: 'com.example.interactive.RunnerTests',
  );
}
